### PR TITLE
option to guess base path: use parent of map directory as base path

### PR DESCRIPTION
**Pull request by illwieckz**
I made this option to make easy to test multiple games. Basically I extracted all pk3 from each game I have as one unpacked directory per game. So, opening `some/path/to/maps/castle.map` will use `some/path/to` as base path/

Note: I don't know how to disable the basepath option when this one is enabled.

### CODE REVIEW

**Comment by illwieckz** [comment]
Hmm, I did the base path guess in `execute` so all function calls get it but shaders are not loaded right.

I also hacked some stuff to pass the guessed base path to `Reload_shader` but this does not work better.

**Comment by SomaZ** [comment]
Pls remove the hack and store the guessed path in the scene as custom property instead.

**Comment by illwieckz** [comment]
I'm looking for a better way to do it, but I'm not sure storing it in a custom property is the right way to do it. Storing this as a scene property would make blender saving the string within the scene if the file had to be saved, while this feature, as implemented in other software, is only a variable that is only used at run time.

**Comment by SomaZ** [comment]
The new main branch has path guessing when theres no configured base and mod paths. This PR is superseded now. Thanks for the suggested solution. Took inspirations from this PR.

**Pull request closed without merging**
